name: one-ck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']
        clickhouse-version: ['20.8', '20.12','21.1','21.3','21.5','21.7','21.9','21.11','22.1','22.3']
    name: PHP ${{ matrix.php-versions }} - clickhouse ${{ matrix.clickhouse-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          ini-values: opcache.jit_buffer_size=256M, opcache.jit=1205, pcre.jit=1, opcache.enable=1, opcache.enable_cli=1
      - name: Check PHP Version
        run: php -v && php -i | grep opcache
      - name: Install Clickhouse
        run: docker run -p 127.0.0.1:9000:9000 -p 127.0.0.1:8123:8123 -d --name some-clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server:${{ matrix.clickhouse-version }}
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Execute tests
        run: php test.php
